Check job outcome

diff --git a/.github/workflows/make-release-artifacts.yml b/.github/workflows/make-release-artifacts.yml
--- a/.github/workflows/make-release-artifacts.yml
+++ b/.github/workflows/make-release-artifacts.yml
@@ -26,4 +26,9 @@ jobs:
     needs: [run]
     runs-on: ubuntu-latest
     steps:
-        - run: echo "done"
+      - run: |
+          if [ "${{ needs.run.result }}" == "failure" ]; then
+            echo "Release artifacts job failed!"
+            exit 1
+          fi
+          echo "All good."
